apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: restore-s3-demo
  namespace: default
spec:
  backupFilename: default-s3-backup-demo-df56e4f4-d5f6-4b9d-8a78-b8c89757df30-2020-08-27T09#59#53-07#00.tar.gz
  storageLocation:
    s3:
      credentialSecretName: creds
      bucketName: rajashree-backup-test
      folder: ecm1
      region: us-west-2
      endpoint: s3.us-west-2.amazonaws.com
  encryptionConfigName: test-encryptionconfig